name: Google Lighthouse audit
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.titaniumringsforever.com/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      # 'report' is hard-coded as the output folder
      with:
        name: report
        path: './report'
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: _reports/lighthouse-audit
    - name: Move HTML report into place
      run: mv report/*.html _reports/ && rm -rf report
    - name: Commit report
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Google Lighthouse audit
    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: report