name: Google Lighthouse audit
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.titaniumringsforever.com/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: _reports/lighthouse-audit