name: Link checker

on:
  push:
    branches:
      - master
  schedule:
    # Every Monday at 2:00 AM.
    - cron: '0 2 * * FRI'
    # At midnight on Jan. 1 of every year.
    - cron:  '0 0 1 1 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Report broken links
        uses: urlstechie/urlchecker-action@0.2.1
        with:
          # A comma-separated list of file types to cover in the URL checks
          file_types: .html

          # The timeout seconds to provide to requests, defaults to 5 seconds
          timeout: 5

          # How many times to retry a failed request (each is logged, defaults to 1)
          retry_count: 1