name: Screenshot the website
on: push

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        width: [1200, 992, 768, 600]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Screenshot website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://www.titaniumringsforever.com/
        destination: screenshot-${{ matrix.width }}.png
        delay: 10 # seconds
        width: ${{ matrix.width }}
        full-page: true
        path: screenshots
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: _reports/screenshots