name: Screenshot the website
on:
  push:
    branches:
      - master

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Screenshot website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://www.titaniumringsforever.com/
        destination: screenshot-${{ matrix.os }}.png
        full-page: true