name: Screenshot the website
on: push

jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Screenshot website
      uses: swinton/screenshot-website@v1.x
      with:
        name: screenshots
        source: https://www.titaniumringsforever.com/
        destination: screenshot.png
        delay: 10 # seconds
        full-page: true
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: _reports/screenshots
    - name: Commit screenshots
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated screenshots of website
    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        path: screenshot.png