name: Screenshot the website
on: push

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Screenshot website
      uses: swinton/screenshot-website@v1.x
      with:
        name: screenshot
        source: https://www.titaniumringsforever.com/
        destination: screenshot-${{ matrix.os }}.png
        delay: 10 # seconds
        full-page: true
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: _reports
    - name: Commit screenshots
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated screenshot of website
    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: screenshot