name: Sitemap submitter

on:
  workflow_run:
    workflows: ["Sitemap generator"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    # see https://github.community/t/workflow-run-completed-event-triggered-by-failed-workflow/128001
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
      - name: Submit sitemap
        id: submit-sitemap
        uses: repetitive/actions/submit-sitemap@master
        with:
          agrs: https://www.titaniumringsforever.com/sitemap.xml
