name: Markdown table of contents generator

on:
  push:
    paths: ['README.md']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/ekalinin/github-markdown-toc.go/releases/download/1.1.0/gh-md-toc.linux.amd64.tgz
          tar xzvf gh-md-toc.linux.amd64.tgz
          ./gh-md-toc --insert --no-backup --start-depth=2 README.md
          rm ./gh-md-toc && rm gh-md-toc.linux.amd64.tgz
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update to README TOC